/// Flutter icons MyVoFo
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyVoFo
///      fonts:
///       - asset: fonts/MyVoFo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyVoFo {
  MyVoFo._();

  static const _kFontFam = 'MyVoFo';
  static const String? _kFontPkg = null;

  static const IconData Home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Add = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Message = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Notification = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Listen = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Repeat = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Heart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Comment = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
